apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinsuranceapp-az
  labels:
    app: myinsuranceapp-az
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myinsuranceapp-az
  template:
    metadata:
      labels:
        app: myinsuranceapp-az
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: myinsuranceapp-az
        image: risunmyinsuranceapp.azurecr.io/myinsuranceapp:v3
        ports:
        - name: http
          containerPort: 5000