apiVersion: v1
kind: Service
metadata:
  name: myinsuranceapp-az
  labels:
    app: myinsuranceapp-az
spec:
  type: NodePort
  selector:
    app: myinsuranceapp-az
  ports:
  - port: 5000
    targetPort: http
    nodePort: 32410
    protocol: TCP
    name: http